"""CatDT Template: Full Agent Pipeline (CatDTCamelWorkflow)

Runs the complete 7-agent workflow: SurFF → AdsorbDiff → VSSR-MC → Agent4/5 → NEB → KMC.
Requires: OPENAI_API_KEY environment variable.

This is the most automated mode — provide bulk structure + reaction description,
the LLM agents handle everything else.
"""

import os, sys
from datetime import datetime

# ── Configuration ──────────────────────────────────────────────
CATDT_ROOT = os.environ.get("CATDT_ROOT", os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, CATDT_ROOT)

# Required
BULK_STRUCTURE_PATH = "POSCAR_Cu"         # Bulk crystal structure
REACTION_DESCRIPTION = "CO hydrogenation to methanol on Cu"  # Natural language

# Surface
TOP_N_SURFACES = 3
MULTI_FACET = False                       # True = run all top-N facets independently

# Reconstruction
MC_TEMPERATURE_K = 500.0
MC_TOTAL_SWEEPS = 100
MC_ENERGY_MODEL = "CHGNet"                # "CHGNet" or "UMA"

# Barriers
CALCULATE_BARRIERS = True
NEB_N_FRAMES = 11
NEB_MAX_STEPS = 80

# KMC (optional)
KMC_TEMPERATURE_K = None                  # Set to enable KMC
GAS_PRESSURES = None                      # e.g., {"CO_g": 1.0, "H2_g": 1.0}

# Mechanism search (optional)
ENABLE_MECHANISM_SEARCH = False
MECHANISM_MODE = "agent_guided"           # agent_guided | systematic | both_sequential

# Electrochemical (optional)
POTENTIAL_SHE = None                      # V vs SHE
PH = None

# Output
OUTPUT_DIR = os.path.join("output", "catdt_workflow", datetime.now().strftime("%Y%m%d_%H%M%S"))

# ── Verify LLM key ────────────────────────────────────────────
if not os.environ.get("OPENAI_API_KEY"):
    print("ERROR: OPENAI_API_KEY environment variable not set.")
    print("The full pipeline requires an LLM API key.")
    sys.exit(1)

# ── Execution ──────────────────────────────────────────────────
from camel_agents.workflow import CatDTCamelWorkflow

wf = CatDTCamelWorkflow()

config = {
    "bulk_structure_path": BULK_STRUCTURE_PATH,
    "reaction_description": REACTION_DESCRIPTION,
    "output_base_dir": OUTPUT_DIR,
    "top_n_surfaces": TOP_N_SURFACES,
    "multi_facet": MULTI_FACET,
    "mc_temperature_k": MC_TEMPERATURE_K,
    "mc_total_sweeps": MC_TOTAL_SWEEPS,
    "mc_energy_model": MC_ENERGY_MODEL,
    "calculate_barriers": CALCULATE_BARRIERS,
    "neb_n_frames": NEB_N_FRAMES,
    "neb_max_steps": NEB_MAX_STEPS,
    "enable_mechanism_search": ENABLE_MECHANISM_SEARCH,
    "mechanism_exploration_mode": MECHANISM_MODE,
}

if KMC_TEMPERATURE_K:
    config["kmc_temperature_k"] = KMC_TEMPERATURE_K
if GAS_PRESSURES:
    config["gas_pressures"] = GAS_PRESSURES
if POTENTIAL_SHE is not None:
    config["potential_she"] = POTENTIAL_SHE
    config["ph"] = PH

print(f"Starting CatDT full pipeline...")
print(f"  Bulk: {BULK_STRUCTURE_PATH}")
print(f"  Reaction: {REACTION_DESCRIPTION}")
print(f"  Output: {OUTPUT_DIR}")

result = wf.run(config)

# Print summary
print(f"\n{'='*60}")
print(f"Pipeline complete!")
print(f"  Validation: {result.get('validation_status', '?')}")
print(f"  Iterations: {result.get('pathway_iterations', '?')}")
print(f"  Episode reward: {result.get('episode_reward', '?')}")

if result.get("neb_results"):
    neb = result["neb_results"]
    print(f"\nNEB Results:")
    for step_name, step_data in neb.items():
        if isinstance(step_data, dict):
            ea = step_data.get("activation_energy_forward", "?")
            print(f"  {step_name}: Ea = {ea} eV")

print(f"\nAll outputs in: {OUTPUT_DIR}")
# Visualization is auto-generated by the workflow (Agent 7)
